### PR TITLE
Add 'nanoCLR' to bug_report_tools.yml

### PR DESCRIPTION
**Pull request by CoryCharlton**
## Description
Add 'nanoCLR' to bug_report_tools.yml

## Motivation and Context
I didn't see a spot to report an issue with `nanoCLR` and this feels like the correct spot.

## Types of changes

- [X] Improvement (correction, content improvement, typo fix, formatting)
- [ ] New Content (new document for docs website)
- [ ] Config and build (change in the configuration and build system, has no impact on code or features)

## Checklist

- [ ] My doc follows the code style of this project.
- [X] I have read the [CONTRIBUTING](https://github.com/nanoframework/.github/blob/main/CONTRIBUTING.md) document.

### CODE REVIEW

**Comment by josesimoes** [comment]
I understand your point. The name is what could be confusing. Maybe "virtual nanoCLR" because the nanoCLR is what we usually refer to what is loaded by nanoBooter, meaning the CLR, EE, etc.

**Comment by CoryCharlton** [comment]
> I understand your point. The name is what could be confusing. Maybe "virtual nanoCLR" because the nanoCLR is what we usually refer to what is loaded by nanoBooter, meaning the CLR, EE, etc.

Sure, that or maybe "nanoCLR CLI".

Happy to update it to whatever just let me know.

**Comment by josesimoes** [comment]
Got you and that's indeed a CLI. 😁 The thing is that there are more references to it as "virtual" (including the name in VS) than CLI, so for consistency and coherence I would go with "Virtual nanoCLR".

**Comment by CoryCharlton** [comment]
> Got you and that's indeed a CLI. 😁 The thing is that there are more references to it as "virtual" (including the name in VS) than CLI, so for consistency and coherence I would go with "Virtual nanoCLR".

Done 👍

**Review by josesimoes — APPROVED** [review]

**Pull request merged**
