### PR TITLE
Documentation on versioning and publish workflow

### PR DESCRIPTION
**Pull request by josesimoes**
Proposal for versioning strategy (basically following SemVer)
Proposal for publish/development/release workflow (based on GitFlow branching strategy).

I've been testing and fine tuning the proposed workflow in the nf-debugger repo.

Signed-off-by: José Simões <jose.simoes@eclo.solutions>

### CODE REVIEW

**Comment by networkfusion** [comment]
Seems sensible to me... One thought though, it would be best to do automated real world board tests upon generation of a release candidate, however I am not sure whether I can use a wild card for the version part... It might be that I can run it whenever a new branch is created...

ALSO there should be something in the documentation about cleaning up the release preview branch after the production release and creating a tag on master... otherwise branching may get out of hand...

**Comment by josesimoes** [comment]
> One thought though, it would be best to do automated real world board tests upon generation of a release candidate

Absolutely!! As soon as we can have that working its a must.

> ALSO there should be something in the documentation about cleaning up the release preview branch after the production release once tagged on master... otherwise branching may get out of hand...

Agreed and I've just added that to the production section on the workflow document,

**Comment by networkfusion** [comment]
Also, How do we ensure releases are kept in step when interdependencies are involved e.g. nf-interpreter relies on a specific release of the class libraries and visa versa...

**Comment by josesimoes** [comment]
> Also, How do we ensure releases are kept in step when interdependencies are involved e.g. nf-interpreter relies on a specific release of the class libraries and visa versa...

I don't think there is an automated way of dealing with/checking that...
Because, in reality, nf-interpreter doesn't depend on the managed counterpart of the class libraries. Instead it _has_ to implement the appropriate calls to support whatever ones are required.

**Pull request merged**
